# Generated by Django 6.0.3 on 2026-03-06 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zoneconfig',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='zoneconfig',
            name='light_pin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detectionlog',
            name='person_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detectionlog',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.zoneconfig'),
        ),
        migrations.AlterField(
            model_name='zoneconfig',
            name='col',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zoneconfig',
            name='name',
            field=models.CharField(default='Zone', max_length=50),
        ),
        migrations.AlterField(
            model_name='zoneconfig',
            name='polygon',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='zoneconfig',
            name='row',
            field=models.IntegerField(default=0),
        ),
    ]
