# Generated by Django 6.0.3 on 2026-03-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_zoneconfig_options_zoneconfig_light_pin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('polygon_data', models.JSONField(default=list)),
                ('zone_config', models.JSONField(default=dict)),
                ('total_detections', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='DetectionLog',
        ),
        migrations.DeleteModel(
            name='ZoneConfig',
        ),
    ]
