# Generated by Django 6.0.3 on 2026-03-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_detectionsession_delete_detectionlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_polygon', models.JSONField(default=list)),
                ('sub_zones', models.JSONField(default=list)),
                ('total_zones', models.IntegerField(default=4)),
                ('rows', models.IntegerField(default=2)),
                ('cols', models.IntegerField(default=2)),
                ('is_processing', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='DetectionSession',
        ),
    ]
