# Generated by Django 6.0.3 on 2026-03-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_videosession_delete_detectionsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Zone', max_length=100)),
                ('polygon_points', models.JSONField(default=list)),
                ('num_rows', models.IntegerField(default=2)),
                ('num_cols', models.IntegerField(default=2)),
                ('sub_zones', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='VideoSession',
        ),
    ]
